apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway-list-service.fullname" . }}
  labels:
    {{- include "gateway-list-service.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: "3000"
  REDIS_HOST: {{ .Values.config.redis.host | quote }}
  REDIS_PORT: {{ .Values.config.redis.port | quote }}
  REDIS_DB: {{ .Values.config.redis.db | quote }}
  CACHE_PRIMARY_TTL: {{ .Values.config.cache.primaryTtl | quote }}
  CACHE_STALE_TTL: {{ .Values.config.cache.staleTtl | quote }}
  MANAGER_API_URL: {{ .Values.config.managerApi.url | quote }}
  WORKER_INTERVAL_MS: {{ .Values.config.workerConfig.intervalMs | quote }}
  WORKER_TIMEOUT_MS: {{ .Values.config.workerConfig.timeoutMs | quote }}
  SITES: {{ .Values.config.sites | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
