apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway-list-service.fullname" . }}-secret
  labels:
    {{- include "gateway-list-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.redis.password }}
  redis-password: {{ .Values.config.redis.password | b64enc | quote }}
  {{- else }}
  redis-password: {{ "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.managerApi.token }}
  internal-api-token: {{ .Values.config.managerApi.token | b64enc | quote }}
  {{- else }}
  internal-api-token: {{ "change-me" | b64enc | quote }}
  {{- end }}
